import React from 'react';
class Wet extends React.Component {
    render() {
        return (
            <>
            <div class="wet1"> </div>

          <div class="wet2"><h5>Wet waste or organic waste such as Vegetable peels, food leftovers, etc., constitute about 50% of the overall waste stream. Dumping of Organic wastes at landfills leads to formation of noxious fumes that adds to green- house gases and also pollutes land, water bodies. This can be avoided by properly managing wet waste through processes that are environmentally friendly such as composting or by feeding the Pre-Conditioned wet-waste to Bio-gas plants.</h5>
          </div>

<div class="weth1">Garden Waste</div>
           <div class="wet3">
          <div class="wet4"><img src="assets/img/garden.png"></img></div>
          <div class="wet5">Tech Parks, large residential communities and event grounds have large landscapes and gardens. These landscapes and gardens produce bulk quantity of organic waste such as leaves, twigs and branches which requires a substantial space for processing. 
          Earth Recycler offers pick up on demand service for garden waste which can be further processed by windrow composting at our centralized waste management facility.
          </div> </div>
          <div class="weth">Composting</div>
         
          <div class="wet6"><img src="assets/img/composting.png"></img></div>
          <div class="wet7">Composting is a environment friendly solution to process organic/wet and garden waste. Wet waste  is converted into compost/vermicompost through conventional, semi-automated or fully automated composting processes. Composting is an aerobic degradation of organic matter resulting in highly nutrient compost.
          At Earth Recyclers we strive for efficiency, cost reduction, highest return on investment and investment security with less risk. Depending on the space and economical availability we recommend the best suitable composting method. There are different forms of composting such as conventional windrow composting, tank composting, vermi-composting, semi-automated and fully automated composting. 
          Composting is simple but when it comes to managing large quantity of wet waste, its better handled by professionals. At Earth Recyclers, we ensure continuous processing and provide ideal condition for the micro organisms to thrive in order to achieve controlled composting which produces best quality  compost.
          </div>


          <div class="wet10">Windrow Composting</div>
          <div class="full1">
          <div class="fully"><img src="assets/img/fully-automatic.png"/></div>
          <div class="wet11">Windrow composting is a simple and versatile method for managing large volumes of garden waste and organic waste generated by communities, food processing industries, and even can handle grease and animal byproducts. Windrow composting becomes economically and technically attractive due to its relatively simple technology and good performance. 

          </div></div>
          <div class="wet10">Conventional Composting – Tank Method
          </div>
          <div class="full1">
          <div class="fully"><img src="assets/img/fully-automatic.png"/></div>
          <div class="wet11">This method of composting involves the construction of  simple rectangular brick tank with enough spaces maintained between the bricks for necessary aeration. Involves less maintenance and is comparatively less expensive on setting up the infrastructure and machineries. Convert your food waste and organics into the best quality manure.  If space is not a constraint and the organic waste generation is high, this is the most robust, long lasting composting method as this will benefit both you and the environment. 


          </div></div>
          
          <div class="wet10">Vermi Composting </div>
          <div class="full1">
          <div class="fully"><img src="assets/img/vermi-composting.png"/></div>
          <div class="wet11">Vermicomposting is a type of composting in which earthworms are used to enhance the process of organic waste conversion and produce a better end-product called vermi-compost. It is a mesophilic process utilizing microorganisms and earthworms. Vermicomposting can be done on small and large scales which can give high nutrient castings which is also loaded with the microorganisms that nourishes and makes soil highly fertile. Vermicompost is often used as top or side dressing for most demanding and deserving plants. 


          </div></div>
          
          <div class="wet10">Semi – Automated Organic Waste Convertor
          </div>
          <div class="full1">
          <div class="fully"><img src="assets/img/fully-automatic.png"/></div>
          <div class="wet11">Best suited for Tech Parks, large residential communities, hotels, institutions and commercial spaces where space is a constraint to construct conventional composting yards . The semi automated OWC is less in maintenance and reduces the space requirement to a bare minimum. This system processes your organic waste such as kitchen waste, garden waste or food processing waste by converting  into rich compost, thus saving it from rotting in the landfill. The processing time is less and the machine is fast, efficient and easy to install. It is also simple to use and can be operated after minimal training.


          </div></div>
          <div class="wet10">Fully Automated Organic Waste Convertor

          </div>
          <div class="full1">
          <div class="fully"><img src="assets/img/fully-automatic.png"/></div>
          <div class="wet11">Fully Automated OWC is best suited for Tech Parks, large residential communities, hotels, institutions and commercial spaces with space constraints but still are environmentally passionate and are mandated to be compliant to the MSW 2016 Rule. These fully automatic machines are compact and can be placed in small rooms, roof top or the basement. These are plug and play composting machines which process all kinds of organic waste into compost within 24 hours, thus ensuring that none of your organic waste ends up in landfills.</div>
          </div>
          
          <div class="wet12">Biogas</div>

          <div class="wet14"><img src="assets/img/biog.png"/></div>
          <div class="wet13">Biogas plants are waste-to-energy plants that convert organic waste into methane. Biogas plants rely on anaerobic digestion, a fermentation process in which organic waste is digested by microbes to produce methane (Biogas). 
          Earth Recycler’s bio-gas plants are robust and durable that completely processes organic waste in the shortest possible time with less maintenance costs. We stand with best understanding of the entire process, from the disposal of waste and other raw materials, through processing, to delivery of the final product. 
          Bio-gas plants are best suited for Restaurants, hotels and food industries which generate large amount of food waste and are looking for significant long-term organic waste management solution in addition to being environmentally responsible. We offer biogas plants of different capacity from as small as 0.5 cubic meter in size.</div>
         
        <div class="wet15">Features that make our biogas plants unique and most sought after are:
        </div>
        <div class="wet17">
<div class="wet16"><div><img src="assets/img/biologo2.png"></img></div>
        <div class="wetcon20">Reduction of carbon emissions through production of naturally occurring methane.
        </div></div>
        
        <div class="wet16"><img src="assets/img/biogaslogo4.png"></img><div class="wetcon20">Elimination of odour and pests issues that are caused by the decomposition of organic material.
        </div></div>
        <div class="wet16"><img src="assets/img/fertilizer (1).png"></img><div class="wetcon20">Transformation of organic wastes into high quality fertilizer. The fertilizer which comes from a bio-gas plant contains three times more nitrogen than the best compost made through open air digestion.
        </div></div>
        <div class="wet16"><img src="assets/img/worm.png"></img><div class="wetcon20">Aesthetic design that focusses in hygiene that reduces breeding of pathogens, worms and flies.
        </div></div>
        <div class="wet16"><img src="assets/img/biolg.png"></img><div class="wetcon20">Complete digestion of sludge which eliminates breeding of pathogens.
        </div></div>
        <div class="wet16"><img src="assets/img/biogaslogo3.png"></img><div class="wetcon20">Biogas could increasingly reduce dependency on LPG & can take part load of power requirements. 
        </div></div></div>





            </>
            );
        }
    }
    export default Wet;